{% set name = "rpcsvc-proto" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thkukuk/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 81c3aa27edb5d8a18ef027081ebb984234d5b5860c65bd99d4ac8f03145a558b

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - libtool

test:
  commands:
    - rpcgen --help
    - test -f $PREFIX/bin/rpcgen  # [unix]

about:
  home: https://github.com/thkukuk/rpcsvc-proto
  summary: rpcsvc protocol definitions from glibc 
  description: |
    This package contains rpcsvc proto.x files from glibc, which are
    missing in libtirpc. Additional it contains rpcgen, which is needed
    to create header files and sources from protocol files.
    This package is only needed, if glibc is installed without the
    deprecated sunrpc functionality and libtirpc should replace it.
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  dev_url: https://github.com/thkukuk/rpcsvc-proto
  doc_url: https://github.com/thkukuk/rpcsvc-proto
